const countries = {
  Amharic: "am-ET",
  Arabic: "ar-SA",
  Bielarus: "be-BY",
  Bemba: "bem-ZM",
  Bislama: "bi-VU",
  Bajan: "bjs-BB",
  Bengali: "bn-IN",
  Tibetan: "bo-CN",
  Breton: "br-FR",
  Bosnian: "bs-BA",
  Catalan: "ca-ES",
  Coptic: "cop-EG",
  Czech: "cs-CZ",
  Welsh: "cy-GB",
  Danish: "da-DK",
  Dzongkha: "dz-BT",
  German: "de-DE",
  Maldivian: "dv-MV",
  Greek: "el-GR",
  English: "en-GB",
  Spanish: "es-ES",
  Estonian: "et-EE",
  Basque: "eu-ES",
  Persian: "fa-IR",
  Finnish: "fi-FI",
  Fanagalo: "fn-FNG",
  Faroese: "fo-FO",
  French: "fr-FR",
  Galician: "gl-ES",
  Gujarati: "gu-IN",
  Hausa: "ha-NE",
  Hebrew: "he-IL",
  Hindi: "hi-IN",
  Croatian: "hr-HR",
  Hungarian: "hu-HU",
  Indonesian: "id-ID",
  Icelandic: "is-IS",
  Italian: "it-IT",
  Japanese: "ja-JP",
  Kazakh: "kk-KZ",
  Khmer: "km-KM",
  Kannada: "kn-IN",
  Korean: "ko-KR",
  Kurdish: "ku-TR",
  Kyrgyz: "ky-KG",
  Latin: "la-VA",
  Lao: "lo-LA",
  Latvian: "lv-LV",
  Mende: "men-SL",
  Malagasy: "mg-MG",
  Maori: "mi-NZ",
  Malay: "ms-MY",
  Maltese: "mt-MT",
  Burmese: "my-MM",
  Nepali: "ne-NP",
  Niuean: "niu-NU",
  Dutch: "nl-NL",
  Norwegian: "no-NO",
  Nyanja: "ny-MW",
  Pakistani: "ur-PK",
  Palauan: "pau-PW",
  Panjabi: "pa-IN",
  Pashto: "ps-PK",
  Pijin: "pis-SB",
  Polish: "pl-PL",
  Portuguese: "pt-PT",
  Kirundi: "rn-BI",
  Romanian: "ro-RO",
  Russian: "ru-RU",
  Sango: "sg-CF",
  Sinhala: "si-LK",
  Slovak: "sk-SK",
  Samoan: "sm-WS",
  Shona: "sn-ZW",
  Somali: "so-SO",
  Albanian: "sq-AL",
  Serbian: "sr-RS",
  Swedish: "sv-SE",
  Swahili: "sw-SZ",
  Tamil: "ta-LK",
  Telugu: "te-IN",
  Tetum: "tet-TL",
  Tajik: "tg-TJ",
  Thai: "th-TH",
  Tigrinya: "ti-TI",
  Turkmen: "tk-TM",
  Tagalog: "tl-PH",
  Tswana: "tn-BW",
  Tongan: "to-TO",
  Turkish: "tr-TR",
  Ukrainian: "uk-UA",
  Uzbek: "uz-UZ",
  Vietnamese: "vi-VN",
  Wolof: "wo-SN",
  Xhosa: "xh-ZA",
  Yiddish: "yi-YD",
  Zulu: "zu-ZA",
};

module.exports = { countries };

// const countries = {
//   "am-ET": "Amharic",
//   "ar-SA": "Arabic",
//   "be-BY": "Bielarus",
//   "bem-ZM": "Bemba",
//   "bi-VU": "Bislama",
//   "bjs-BB": "Bajan",
//   "bn-IN": "Bengali",
//   "bo-CN": "Tibetan",
//   "br-FR": "Breton",
//   "bs-BA": "Bosnian",
//   "ca-ES": "Catalan",
//   "cop-EG": "Coptic",
//   "cs-CZ": "Czech",
//   "cy-GB": "Welsh",
//   "da-DK": "Danish",
//   "dz-BT": "Dzongkha",
//   "de-DE": "German",
//   "dv-MV": "Maldivian",
//   "el-GR": "Greek",
//   "en-GB": "English",
//   "es-ES": "Spanish",
//   "et-EE": "Estonian",
//   "eu-ES": "Basque",
//   "fa-IR": "Persian",
//   "fi-FI": "Finnish",
//   "fn-FNG": "Fanagalo",
//   "fo-FO": "Faroese",
//   "fr-FR": "French",
//   "gl-ES": "Galician",
//   "gu-IN": "Gujarati",
//   "ha-NE": "Hausa",
//   "he-IL": "Hebrew",
//   "hi-IN": "Hindi",
//   "hr-HR": "Croatian",
//   "hu-HU": "Hungarian",
//   "id-ID": "Indonesian",
//   "is-IS": "Icelandic",
//   "it-IT": "Italian",
//   "ja-JP": "Japanese",
//   "kk-KZ": "Kazakh",
//   "km-KM": "Khmer",
//   "kn-IN": "Kannada",
//   "ko-KR": "Korean",
//   "ku-TR": "Kurdish",
//   "ky-KG": "Kyrgyz",
//   "la-VA": "Latin",
//   "lo-LA": "Lao",
//   "lv-LV": "Latvian",
//   "men-SL": "Mende",
//   "mg-MG": "Malagasy",
//   "mi-NZ": "Maori",
//   "ms-MY": "Malay",
//   "mt-MT": "Maltese",
//   "my-MM": "Burmese",
//   "ne-NP": "Nepali",
//   "niu-NU": "Niuean",
//   "nl-NL": "Dutch",
//   "no-NO": "Norwegian",
//   "ny-MW": "Nyanja",
//   "ur-PK": "Pakistani",
//   "pau-PW": "Palauan",
//   "pa-IN": "Panjabi",
//   "ps-PK": "Pashto",
//   "pis-SB": "Pijin",
//   "pl-PL": "Polish",
//   "pt-PT": "Portuguese",
//   "rn-BI": "Kirundi",
//   "ro-RO": "Romanian",
//   "ru-RU": "Russian",
//   "sg-CF": "Sango",
//   "si-LK": "Sinhala",
//   "sk-SK": "Slovak",
//   "sm-WS": "Samoan",
//   "sn-ZW": "Shona",
//   "so-SO": "Somali",
//   "sq-AL": "Albanian",
//   "sr-RS": "Serbian",
//   "sv-SE": "Swedish",
//   "sw-SZ": "Swahili",
//   "ta-LK": "Tamil",
//   "te-IN": "Telugu",
//   "tet-TL": "Tetum",
//   "tg-TJ": "Tajik",
//   "th-TH": "Thai",
//   "ti-TI": "Tigrinya",
//   "tk-TM": "Turkmen",
//   "tl-PH": "Tagalog",
//   "tn-BW": "Tswana",
//   "to-TO": "Tongan",
//   "tr-TR": "Turkish",
//   "uk-UA": "Ukrainian",
//   "uz-UZ": "Uzbek",
//   "vi-VN": "Vietnamese",
//   "wo-SN": "Wolof",
//   "xh-ZA": "Xhosa",
//   "yi-YD": "Yiddish",
//   "zu-ZA": "Zulu",
// };
